apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: tester123
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tester123
  annotations:
    kubernetes.io/service-account.name: "tester123"
type: kubernetes.io/service-account-token
