#
# Init 容器可以包含一些安装过程中应用容器中不存在的实用工具或个性化代码；
# Init 容器可以安全地运行这些工具，避免这些工具导致应用镜像的安全性降低；
# Init容器可以以root身份运行，执行一些高权限命令；
# Init容器相关操作执行完成以后即退出，不会给业务容器带来安全隐患。


# 它们总是运行到完成；
# 上一个运行完成才会运行下一个；
# 如果 Pod 的 Init 容器失败，Kubernetes 会不断地重启该 Pod，直到 Init 容器成功为止，但是Pod对应的 restartPolicy 值为 Never，Kubernetes 不会重新启动 Pod。
# Init 容器不支持 lifecycle、livenessProbe、readinessProbe 和 startupProbe




apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-inicontainer
  name: deploy-inicontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-inicontainer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-inicontainer
    spec:
      initContainers: 
      - name: fix-permissions
        image: busybox
        command: 
        - sh
        - -c
        - "mkdir -pv /usr/share/elasticsearch/; touch /usr/share/elasticsearch/123.log; chown -R 1000:1000 /usr/share/elasticsearch/123.log"
        securityContext: 
          privileged: true
        volumeMounts: 
        - name: data
          mountPath: /usr/share/elasticsearch/
      - name: increase-vm-max-map
        image: busybox
        command: 
        - sh
        - -c
        - "sysctl -w vm.max_map_count=262144"
        securityContext: 
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: 
        - sh
        - -c
        - "ulimit -n 65536"
        securityContext: 
          privileged: true
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: 
          limits: 
            cpu: 1000m
          requests: 
            cpu: 100m
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html/
      volumes: 
      - name: data
        emptyDir: {}
status: {}
