apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: echo-2
spec:
  ttlSecondsAfterFinished: 100 # job在执行结束之后（状态为complated或Failed）自动清理。设置为0表示执行结束后立即删除
  activeDeadlineSeconds: 50 # Job的最长运行时间，一旦 Job 运行时间达到activeDeadlineSeconds 秒，其所有运行中的 Pod 都会被终止， 并且 Job 的状态更新为 type: Failed 及 reason: DeadlineExceeded。
  backoffLimit: 4 # 如果任务失败，失败多少次后不再执行
  completions: 5 # 有多少个Pod执行成功，认为任务是成功的，为空则和parallelism数值一致
  parallelism: 3 # 并发执行任务的数量， 如果parallelism数值大于未完成任务数，只会创建未完成的数量，比如completions是4，并发是3，第一次创建3个Pod任务第二次创建1个Pod任务。
  suspend: false # 1.21+ 创建任务后暂停Pod，改为false才会执行
  template:
    metadata:
      creationTimestamp: null
    spec:
      affinity:
        podAntiAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution: 
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: busybox
        name: echo
        command: 
        - sh
        - -c 
        - date
        resources: {}
      restartPolicy: Never
status: {}
