apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: must-be-diff-nodes
  name: must-be-diff-nodes
  namespace: kube-public
spec:
  replicas: 3
  selector:
    matchLabels:
      app: must-be-diff-nodes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: must-be-diff-nodes
    spec:
      affinity: 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:  # Pod选择器配置，可以配置多个
              matchExpressions:  # 和节点亲和力一致
              - key: app
                operator: In
                values: 
                - must-be-diff-nodes
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
