# 应用和缓存尽量部署在同一个域内
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-server
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-server
    spec:
      affinity: 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:  # Pod选择器配置，可以配置多个
              matchExpressions:  # 和节点亲和力一致
              - key: app
                operator: In
                values: 
                - web-server
            topologyKey: kubernetes.io/hostname
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector: 
                matchExpressions: 
                - key: app
                  operator: In
                  values: 
                  - redis-cache
              topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx:1.16-alpine
        name: nginx
        resources: {}
status: {}
