apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: with-node-affinity
  name: with-node-affinity
spec:
  containers:
  - image: nginx
    name: with-node-affinity
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:  # 硬亲和力配置
        nodeSelectorTerms:  # 节点选择器配置，可以配置多个matchExpression（满足其一），每个matchExpression下可以配置多个key、value类型的选择器（都需要满足），其中values可以配置多个（满足其一）
        - matchExpressions: 
          - key: ssd
            operator: In
            values: 
            - "true"
        - matchExpressions: 
          - key: subnet
            operator: In
            values: 
            - "172-16-0"
      preferredDuringSchedulingIgnoredDuringExecution: # 软亲和力配置
      - weight: 1  # 软亲和力权重，权重越高优先级越大，范围1-100
        preference:  # 软亲和力配置项，和weight同级，可以配置多个，matchExpresssions和硬亲和力一致
          matchExpressions: 
          - key: ssd
            operator: In  # In: 相当于key = value的形式
            values:       # NotIn: 相当于key != value的形式
            - "true"      # Exists: 节点存在label的key为指定值即可，不能配置values字段
status: {}                # DoseNotExist: 节点不存在label的key为指定的值即可，不能配置values字段
                          # Gt: 大于value指定的值
                          # Lt:  小于value指定的值
