apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: with-pod-affinity
  name: with-pod-affinity
spec:
  affinity: 
    podAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
      - labelSelector:  # Pod选择器配置，可以配置多个
          matchExpressions:  # 和节点亲和力一致
          - key: security
            operator: In
            values: 
            - S1
        topologyKey: failure-domain.beta.kubernetes.io/zone # 匹配的拓扑域的key，也就是节点上label的key，key的value相同的为同一个域，可以用于标注不同的机房和地区。
        namespaces:  # 和哪个命名空间的Pod进行匹配，为空则为当前命名空间
        - default
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector: 
            matchExpressions: 
            - key: security
              operator: In
              values: 
              - S2
          namespaces: 
          - default
          topologyKey: failure-domain.beta.kubernetes.io/zone 
  containers:
  - image: nginx
    name: with-pod-affinity
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
