# 同一个应用不同副本固定节点
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-cache
  name: redis-cache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-cache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-cache
    spec:
      # nodeSelector: 
      #   app: redis-cache
      affinity: 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:  # Pod选择器配置，可以配置多个
              matchExpressions:  # 和节点亲和力一致
              - key: app
                operator: In
                values: 
                - redis-cache
            topologyKey: kubernetes.io/hostname
      containers:
      - image: redis:3.2-alpine
        name: redis
        resources: {}
status: {}
