apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pod-log-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods
  verbs:
  - get
  - list
  - watch
