apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: tester123
  namespace: kube-users
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: tester456
